"""add rooms

Revision ID: 3e378545ba79
Revises: e064058f89cf
Create Date: 2026-04-21 22:50:42.403292

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3e378545ba79"
down_revision: Union[str, Sequence[str], None] = "e064058f89cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")  # type: ignore
    # ### end Alembic commands ###
